### ISSUE TITLE
Fix (configure) Jest (in CRA)

### ISSUE THREAD

**Issue by retarsis** [retarsis/monoreact#127]
Currently, CRA doesn't provide the possibility to configure `moduleDirectories`.

It means when we run `react-scripts test` we will have this
![image](https://user-images.githubusercontent.com/21989873/78506952-f13ec580-7785-11ea-9ed1-2271f64ec518.png)

`moduleNameMapper` doesn't look like a proper solution

It'd be nice to have an extendable solution where you don’t have to manage with your hands.

**Comment by maktarsis** [comment]
another stone in the garden of `moduleNameMapper`:
tests will fall anyway if you use `ts paths`

**Comment by maktarsis** [comment]
I think, it'd be totally okay if `re-space` will have its own webpack bundler.
And it will fix this issue.

**Comment by retarsis** [comment]
seems like after bump `jest` to v26 the issue has disappear
